#!/usr/bin/env python3
"""
scaffold_flow.py — emit a ready-to-import Node-RED tab using Workflow Kit subflows

Examples:
  python3 scaffold_flow.py --type sweep --name "My Sweep" --path /api/automation/ops-digest
  python3 scaffold_flow.py --type webhook --name "Wix Hook" --url /webhook/my-event
  python3 scaffold_flow.py --type dual --name "Score+Qualify" --gas-action scoreAndSyncQualifiedRows \\
      --path /api/automation/lead-qualification
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")[:40]


def sweep_tab(name: str, path: str, cron: str) -> list:
    sid = slug(name)
    tab = f"tab_scaf_{sid}"
    return [
        {
            "id": tab,
            "type": "tab",
            "label": name,
            "disabled": False,
            "info": f"Scaffold: Safe Cron → Leads API `{path}` → Slack on failure.\nGenerated by scaffold_flow.py",
        },
        {
            "id": f"{sid}_inject",
            "type": "inject",
            "z": tab,
            "name": f"⏰ {cron or 'Manual'}",
            "props": [
                {"p": "payload"},
                {"p": "leadsPath", "v": path, "vt": "str"},
                {"p": "method", "v": "POST", "vt": "str"},
            ],
            "repeat": "" if cron else "",
            "crontab": cron or "",
            "once": False,
            "topic": sid,
            "payload": "{}",
            "payloadType": "json",
            "x": 160,
            "y": 120,
            "wires": [[f"{sid}_gate"]],
        },
        {
            "id": f"{sid}_manual",
            "type": "inject",
            "z": tab,
            "name": "▶ Run Now",
            "props": [
                {"p": "payload"},
                {"p": "leadsPath", "v": path, "vt": "str"},
                {"p": "method", "v": "POST", "vt": "str"},
            ],
            "repeat": "",
            "crontab": "",
            "once": False,
            "topic": sid,
            "payload": "{}",
            "payloadType": "json",
            "x": 150,
            "y": 180,
            "wires": [[f"{sid}_gate"]],
        },
        {
            "id": f"{sid}_gate",
            "type": "subflow-safe-cron",
            "z": tab,
            "name": "Safe Gate",
            "x": 360,
            "y": 140,
            "wires": [[f"{sid}_leads"], []],
        },
        {
            "id": f"{sid}_leads",
            "type": "subflow-leads-api",
            "z": tab,
            "name": "Leads Call",
            "x": 560,
            "y": 140,
            "wires": [[f"{sid}_ok"], [f"{sid}_fail"]],
        },
        {
            "id": f"{sid}_ok",
            "type": "debug",
            "z": tab,
            "name": "OK",
            "active": True,
            "tosidebar": True,
            "complete": "payload",
            "x": 760,
            "y": 100,
            "wires": [],
        },
        {
            "id": f"{sid}_fail",
            "type": "function",
            "z": tab,
            "name": "Fail → Slack",
            "func": f"msg.payload = {{ text: '⚠️ *{name} failed*\\n' + JSON.stringify(msg.payload||{{}}).slice(0,400), channel: '#scraper-errors' }};\nreturn msg;",
            "outputs": 1,
            "x": 760,
            "y": 180,
            "wires": [[f"{sid}_slack"]],
        },
        {
            "id": f"{sid}_slack",
            "type": "subflow-slack-notify",
            "z": tab,
            "name": "Slack",
            "x": 960,
            "y": 180,
            "wires": [[], []],
        },
    ]


def webhook_tab(name: str, url: str) -> list:
    sid = slug(name)
    tab = f"tab_scaf_{sid}"
    return [
        {
            "id": tab,
            "type": "tab",
            "label": name,
            "disabled": False,
            "info": f"Scaffold: HTTP `{url}` → HMAC → process → Slack",
        },
        {
            "id": f"{sid}_http",
            "type": "http in",
            "z": tab,
            "name": f"POST {url}",
            "url": url,
            "method": "post",
            "upload": False,
            "swaggerDoc": "",
            "x": 160,
            "y": 120,
            "wires": [[f"{sid}_hmac"]],
        },
        {
            "id": f"{sid}_hmac",
            "type": "subflow-hmac-guard",
            "z": tab,
            "name": "HMAC",
            "x": 360,
            "y": 120,
            "wires": [[f"{sid}_work"], [f"{sid}_rej"]],
        },
        {
            "id": f"{sid}_work",
            "type": "function",
            "z": tab,
            "name": "Process",
            "func": "node.status({fill:'green',shape:'dot',text:'ok'});\nmsg.statusCode=200;\nmsg.payload={ok:true,received:true};\nreturn msg;",
            "outputs": 1,
            "x": 560,
            "y": 100,
            "wires": [[f"{sid}_resp"]],
        },
        {
            "id": f"{sid}_rej",
            "type": "function",
            "z": tab,
            "name": "Reject",
            "func": "msg.statusCode=403;\nreturn msg;",
            "outputs": 1,
            "x": 560,
            "y": 160,
            "wires": [[f"{sid}_resp"]],
        },
        {
            "id": f"{sid}_resp",
            "type": "http response",
            "z": tab,
            "name": "Response",
            "statusCode": "",
            "headers": {},
            "x": 780,
            "y": 120,
            "wires": [],
        },
    ]


def dual_tab(name: str, gas_action: str, path: str) -> list:
    sid = slug(name)
    tab = f"tab_scaf_{sid}"
    return [
        {
            "id": tab,
            "type": "tab",
            "label": name,
            "disabled": False,
            "info": f"Scaffold: GAS `{gas_action}` → Leads `{path}`",
        },
        {
            "id": f"{sid}_inject",
            "type": "inject",
            "z": tab,
            "name": "▶ Run",
            "props": [{"p": "payload"}],
            "repeat": "",
            "crontab": "",
            "once": False,
            "topic": sid,
            "payload": json.dumps({"action": gas_action}),
            "payloadType": "json",
            "x": 140,
            "y": 120,
            "wires": [[f"{sid}_gate"]],
        },
        {
            "id": f"{sid}_gate",
            "type": "subflow-safe-cron",
            "z": tab,
            "name": "Gate",
            "x": 320,
            "y": 120,
            "wires": [[f"{sid}_gas"], []],
        },
        {
            "id": f"{sid}_gas",
            "type": "subflow-gas-action",
            "z": tab,
            "name": "GAS",
            "x": 500,
            "y": 120,
            "wires": [[f"{sid}_prep_leads"], [f"{sid}_fail"]],
        },
        {
            "id": f"{sid}_prep_leads",
            "type": "function",
            "z": tab,
            "name": "Prep Leads",
            "func": f"msg.leadsPath='{path}';\nmsg.method='POST';\nmsg.payload=msg.payload||{{}}\nif (typeof msg.payload!=='object') msg.payload={{}};\nreturn msg;",
            "outputs": 1,
            "x": 700,
            "y": 100,
            "wires": [[f"{sid}_leads"]],
        },
        {
            "id": f"{sid}_leads",
            "type": "subflow-leads-api",
            "z": tab,
            "name": "Leads",
            "x": 900,
            "y": 100,
            "wires": [[f"{sid}_ok"], [f"{sid}_fail"]],
        },
        {
            "id": f"{sid}_ok",
            "type": "debug",
            "z": tab,
            "name": "OK",
            "active": True,
            "complete": "payload",
            "x": 1100,
            "y": 80,
            "wires": [],
        },
        {
            "id": f"{sid}_fail",
            "type": "function",
            "z": tab,
            "name": "Fail Slack",
            "func": f"msg.payload={{text:'⚠️ *{name}* failed',channel:'#scraper-errors'}};\nreturn msg;",
            "outputs": 1,
            "x": 900,
            "y": 180,
            "wires": [[f"{sid}_slack"]],
        },
        {
            "id": f"{sid}_slack",
            "type": "subflow-slack-notify",
            "z": tab,
            "name": "Slack",
            "x": 1100,
            "y": 180,
            "wires": [[], []],
        },
    ]


def main():
    ap = argparse.ArgumentParser(description="Scaffold a Node-RED tab using Workflow Kit")
    ap.add_argument("--type", choices=["sweep", "webhook", "dual"], required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--path", default="/api/automation/health", help="Leads API path")
    ap.add_argument("--url", default="/webhook/custom", help="Webhook path")
    ap.add_argument("--gas-action", default="scoreAndSyncQualifiedRows")
    ap.add_argument("--cron", default="", help="Node-RED crontab e.g. '0 9 * * *'")
    ap.add_argument("--out", default="", help="Write path (default scaffolds/<slug>.json)")
    args = ap.parse_args()

    if args.type == "sweep":
        nodes = sweep_tab(args.name, args.path, args.cron)
    elif args.type == "webhook":
        nodes = webhook_tab(args.name, args.url)
    else:
        nodes = dual_tab(args.name, args.gas_action, args.path)

    out = Path(args.out) if args.out else Path("scaffolds") / f"{slug(args.name)}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(nodes, indent=2) + "\n")
    print(f"Wrote {out} ({len(nodes)} nodes)")
    print("Import in Node-RED: Menu → Import → select file → Deploy")
    print("Requires Workflow Kit subflows (python3 deploy_workflow_kit.py)")


if __name__ == "__main__":
    main()
